### ISSUE TITLE
Build script can't find interceptor and environment

### ISSUE THREAD

**Issue by fjbender** [donmahallem/TrapezeClientNgDemo#150]
I'm trying to build the project using the included script.

Expected result: The app is built

Actual result:

The modules `interceptor` and `environment` cannot be found during the `ng` run

```
ERROR in app/app.module.ts:2:32 - error TS2307: Cannot find module './interceptor'.

2 import {TokenInterceptor} from "./interceptor";
                                 ~~~~~~~~~~~~~~~
app/app.module.ts:10:29 - error TS2306: File '/home/florian/trapezeclientngdemo/TrapezeClientNg/src/environments/environment.ts' is not a module.

10 import { environment } from '../environments/environment';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/services/api.service.ts:15:29 - error TS2306: File '/home/florian/trapezeclientngdemo/TrapezeClientNg/src/environments/environment.prod.ts' is not a module.

15 import { environment } from 'src/environments/environment.prod';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.ts:5:29 - error TS2306: File '/home/florian/trapezeclientngdemo/TrapezeClientNg/src/environments/environment.ts' is not a module.

5 import { environment } from './environments/environment';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I tried running it on node 10.16.3 on linux x64 as well as node 12.13.1 on win32 x64.

**Comment by donmahallem** [comment]
Hi. I should have made it more clear in the Readme. This is only a demo repository and specifically altered to work on github pages only. I will update it. 

In the meantime if you want to run the project you want to look at https://github.com/donmahallem/TrapezeClientElectron which is a Desktop Client based on Electron.

The angular [client](https://github.com/donmahallem/TrapezeClientNg) requires a [proxy](https://github.com/donmahallem/TrapezeApiExpressRoute) to circumvent CORS Issues and some short comings of the origin API. For an example how it all comes together look [here](https://github.com/donmahallem/TrapezeClientElectron/blob/master/src/api-server.ts)

Feel free to ask further questions in case you need more directions. I will update the READMEs later today. And might reference a whole tutorial on how to assemble the parts as a whole.

**Comment by fjbender** [comment]
Ahh, that makes sense.

The electron client is running well, thanks! :)

**Comment by donmahallem** [comment]
The electron client has sometimes a race condition at startup I wasnt able to fix yet. Hold alt and inside the menu select reload. This should fix it
